### ISSUE TITLE
i fixing your mod but what is "ZipFile"?

### ISSUE THREAD

**Issue by Davuksr** [Chin0303/Monke-Dimensions#5]
![image](https://github.com/Chin0303/Monke-Dimensions/assets/112632098/addb1b4b-b2ca-476f-869f-14587a349e7d)

**Comment by Chin0303** [comment]
May I know what you are fixing? As far as I know there is nothing broken.

**Comment by anundefineduser** [comment]
the mod isnt broken, utilla is rn

anyways https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile

**Comment by Davuksr** [comment]
> May I know what you are fixing? As far as I know there is nothing broken.

i am fixing your mod yesterday i fixed utilla and started fixing your mod but visual studio don't know what is "zipfile" command so i need answer how to fix this

**Comment by Davuksr** [comment]
> May I know what you are fixing? As far as I know there is nothing broken.

i need System.IO.Compression.ZipFile.dll and add as reference can you send that dll?

**Comment by Davuksr** [comment]
> the mod isnt broken, utilla is rn
> 
> anyways https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile

i fixed utilla yesterday https://cdn.discordapp.com/attachments/1216045650429345862/1216045692770848969/Utilla.dll 
![image](https://github.com/Chin0303/Monke-Dimensions/assets/112632098/6a6b6ceb-6177-4996-a296-9499283ee435)

**Comment by Chin0303** [comment]
No you didn't, you stole haunteds fix.

**Comment by Davuksr** [comment]
> No you didn't, you stole haunteds fix.

i don't know about that

**Comment by Davuksr** [comment]
> No you didn't, you stole haunteds fix.

haunted not has fix
