### ISSUE TITLE
Discord link invalid and cant find unity project for making dimensions

### ISSUE THREAD

**Issue by elliottophatonyt** [Chin0303/Monke-Dimensions#9]
So i saw a youtube video of someone making maps for this mod, and I was trying to find a way to make them. I have unity and all that stuff but I cant find the unity project anywhere on this github page. I also tried to join the discord but it says it is invalid. please fix this

**Comment by Chin0303** [comment]
discord.gg/monkedimensions or https://discord.gg/jpXUvJyX
